export type OutboxStatus='draft'|'uploading'|'ready'|'sent'|'received'|'persisted'|'accepted'|'failed'|'cancelled';
export type OutboxRecord={clientMessageId:string;sessionId:string;text:string;attachments:{id:string;name:string;type?:string;size?:number}[];planMode:'direct'|'plan';createdAt:number;updatedAt?:number;attempts:number;status:OutboxStatus;lastError?:string;nextAttemptAt?:number;retryOf?:string};
const DB='agentdeck-outbox'; const STORE='messages'; const FALLBACK='agentdeck:outbox:fallback'; const MAX=200; const MAX_FAILED=100; const MAX_ATTEMPTS=8;

export class BrowserOutbox {
  private listeners=new Set<()=>void>();
  subscribe(listener:()=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener);}
  private changed(){for(const listener of this.listeners)try{listener();}catch{}}
  private openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(!globalThis.indexedDB)return reject(new Error('IndexedDB unavailable'));const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:'clientMessageId'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async put(record:OutboxRecord){record=validateOutboxRecord({...record,updatedAt:Number(record.updatedAt||Date.now())});if(['persisted','accepted'].includes(record.status))record={...record,text:'',nextAttemptAt:undefined};if(record.attempts>=MAX_ATTEMPTS)record={...record,status:'failed',lastError:record.lastError||'maximum retry attempts reached',nextAttemptAt:undefined};try{const db=await this.openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(record);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();const fallback=this.fallbackList().find(row=>row.clientMessageId===record.clientMessageId);if(!fallback||Number(fallback.updatedAt||0)<=Number(record.updatedAt||0))this.fallbackDelete(record.clientMessageId);await this.trim();this.changed();return true;}catch{const saved=this.fallbackPut(record);if(saved)this.changed();return saved;}}
  async list(sessionId?:string):Promise<OutboxRecord[]>{let rows:OutboxRecord[]=[];try{const db=await this.openDb();rows=await new Promise<OutboxRecord[]>((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});db.close();}catch{}const merged=new Map<string,OutboxRecord>();for(const raw of [...rows,...this.fallbackList()]){const row=validateOutboxRecord({...raw,updatedAt:Number(raw.updatedAt||raw.createdAt||0)});const previous=merged.get(row.clientMessageId);if(!previous||Number(row.updatedAt||0)>Number(previous.updatedAt||0))merged.set(row.clientMessageId,row);}return [...merged.values()].filter(row=>!sessionId||row.sessionId===sessionId).sort((a,b)=>a.createdAt-b.createdAt);}
  async update(id:string,patch:Partial<OutboxRecord>){const current=(await this.list()).find(row=>row.clientMessageId===id);if(current){const terminalBody=['persisted','accepted'].includes(String(patch.status||current.status))?{text:'',nextAttemptAt:undefined}:{};await this.put({...current,...patch,...terminalBody,updatedAt:Date.now()});}}
  async removeBodyAfterPersisted(id:string){const current=(await this.list()).find(row=>row.clientMessageId===id);if(current&&['persisted','accepted'].includes(current.status))await this.put({...current,text:''});}
  retryDelay(attempts:number){return Math.min(30_000,500*2**Math.max(0,attempts-1));}
  private async trim(){const rows=await this.list();const failed=rows.filter(row=>row.status==='failed');for(const row of failed.slice(0,Math.max(0,failed.length-MAX_FAILED)))await this.delete(row.clientMessageId);const remaining=await this.list();for(const row of remaining.filter(row=>['persisted','accepted','cancelled'].includes(row.status)).slice(0,Math.max(0,remaining.length-MAX)))await this.delete(row.clientMessageId);}
  async delete(id:string){try{const db=await this.openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}catch{}this.fallbackDelete(id);this.changed();}
  private fallbackList():OutboxRecord[]{try{const rows=JSON.parse(localStorage.getItem(FALLBACK)||'[]');return Array.isArray(rows)?rows.slice(-50):[];}catch{return[];}}
  private fallbackPut(record:OutboxRecord){try{const rows=this.fallbackList().filter(row=>row.clientMessageId!==record.clientMessageId);rows.push(record);localStorage.setItem(FALLBACK,JSON.stringify(rows.slice(-50)));return true;}catch{return false;}}
  private fallbackDelete(id:string){try{localStorage.setItem(FALLBACK,JSON.stringify(this.fallbackList().filter(row=>row.clientMessageId!==id)));}catch{}}
}
function validateOutboxRecord(record:OutboxRecord){if(!record||!record.clientMessageId||!record.sessionId||!['direct','plan'].includes(record.planMode)||!Array.isArray(record.attachments)||!Number.isInteger(record.attempts)||record.attempts<0)throw new Error('invalid outbox record');return record;}

export class OutboxRetryScheduler{
  private timer:any=null;private scheduling:Promise<void>|null=null;private rerun=false;private generation=0;
  private load:()=>Promise<OutboxRecord[]>;private onDeadline:()=>Promise<void>;private clock:{now:()=>number;setTimeout:(fn:()=>void,ms:number)=>any;clearTimeout:(id:any)=>void};
  constructor(load:()=>Promise<OutboxRecord[]>,onDeadline:()=>Promise<void>,clock:{now:()=>number;setTimeout:(fn:()=>void,ms:number)=>any;clearTimeout:(id:any)=>void}={now:()=>Date.now(),setTimeout:(fn,ms)=>setTimeout(fn,ms),clearTimeout:id=>clearTimeout(id)}){this.load=load;this.onDeadline=onDeadline;this.clock=clock;}
  wake(){this.generation++;if(this.timer){this.clock.clearTimeout(this.timer);this.timer=null;}if(this.scheduling){this.rerun=true;return this.scheduling;}const run=async()=>{do{this.rerun=false;const generation=this.generation;const rows=await this.load();if(generation!==this.generation){this.rerun=true;continue;}const deadlines=rows.filter(r=>!['persisted','accepted','cancelled','failed'].includes(r.status)).map(r=>r.nextAttemptAt||this.clock.now());if(deadlines.length){const delay=Math.max(0,Math.min(...deadlines)-this.clock.now());this.timer=this.clock.setTimeout(()=>{this.timer=null;void this.onDeadline().finally(()=>this.wake());},delay);}}while(this.rerun);};this.scheduling=run().finally(()=>{this.scheduling=null;if(this.rerun)void this.wake();});return this.scheduling;}
  stop(){this.generation++;if(this.timer)this.clock.clearTimeout(this.timer);this.timer=null;}
}
