import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { chmod, mkdir, mkdtemp, readFile, rm, unlink, writeFile } from 'node:fs/promises';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import Database from 'better-sqlite3';

test('Antigravity Runtime releases failed claims and waits through SIGKILL cancellation',async()=>{
  const port=await freePort(),root=await mkdtemp(path.join(os.tmpdir(),'agentdeck-agy-runtime-')),data=path.join(root,'data'),profileId='abcdef0123456789',home=path.join(data,'antigravity-profiles',profileId,'home'),binary=path.join(root,'agy'),pidFile=path.join(root,'agy.pid'),childPidFile=path.join(root,'agy-child.pid'),grandPidFile=path.join(root,'agy-grand.pid'),raceReadyFile=path.join(root,'race-ready'),argsFile=path.join(root,'args');
  await mkdir(home,{recursive:true});
  const env={...process.env,NODE_ENV:'test',DATA_DIR:data,RUNTIME_DATA_DIR:data,RUNTIME_DB:path.join(data,'runtime.sqlite3'),RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(port),SKIP_RUNTIME_BOOTSTRAP:'1',ANTIGRAVITY_BIN:binary,ANTIGRAVITY_STOP_GRACE_MS:'120',ANTIGRAVITY_TURN_TIMEOUT_MS:'5000',ANTIGRAVITY_TEST_BEFORE_SPAWN_DELAY_MS:'100',ANTIGRAVITY_TEST_AFTER_SPAWN_DELAY_MS:'100',RUNTIME_DRAIN_TIMEOUT_MS:'150',HOME:path.join(root,'empty-home'),PATH:`${path.dirname(process.execPath)}:/usr/bin:/bin`};
  const child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env,stdio:['ignore','pipe','pipe']}),output=[];child.stdout.on('data',x=>output.push(String(x)));child.stderr.on('data',x=>output.push(String(x)));
  try{
    await waitHttp(port,'/healthz',child,output);
    await writeFile(path.join(data,'runtime'),'blocks log directory');
    await ensureSession(port,'log-failure',profileId,home);
    assert.equal((await post(port,'/sessions/log-failure/turns',turnBody(profileId,home,'log failure'))).status,200);
    await waitTerminal(port,'log-failure','turn/failed');await assertReleased(port,'log-failure');
    await unlink(path.join(data,'runtime'));

    await ensureSession(port,'binary-failure',profileId,home);
    assert.equal((await post(port,'/sessions/binary-failure/turns',turnBody(profileId,home,'missing binary'))).status,200);
    await waitTerminal(port,'binary-failure','turn/failed');await assertReleased(port,'binary-failure');
    const retry=await post(port,'/sessions/binary-failure/turns',{...turnBody(profileId,home,'missing binary retry'),turnId:'retry-turn',clientMessageId:'retry-message'});assert.equal(retry.status,200,'a pre-spawn failure must not permanently retain the claim');
    await waitTerminalCount(port,'binary-failure','turn/failed',2);await assertReleased(port,'binary-failure');

    await writeFile(binary,`#!/usr/bin/env node\nimport fs from 'node:fs';import path from 'node:path';import{spawn}from'node:child_process';\nconst args=process.argv.slice(2),prompt=args.at(-1)||'',log=args[args.indexOf('--log-file')+1];fs.appendFileSync(${JSON.stringify(argsFile)},args.join(' ')+'\\n');\nif(['STOP','SPAWNRACE','TIMEOUT','SHUTDOWN','DRAIN'].includes(prompt)){fs.writeFileSync(${JSON.stringify(pidFile)},String(process.pid));const c=spawn('/bin/sh',['-c',\"trap '' TERM; sleep 1000 & echo $! > \\\"$GRAND_PID_FILE\\\"; wait\"],{stdio:'ignore',env:{...process.env,GRAND_PID_FILE:${JSON.stringify(grandPidFile)}}});fs.writeFileSync(${JSON.stringify(childPidFile)},String(c.pid));process.on('SIGTERM',()=>{});setInterval(()=>{},1000);}else{const id='ce69f19b-3085-4abf-b514-03b7e4d0813a',dir=path.join(process.env.HOME,'.gemini','antigravity-cli','conversations');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.db'),'');fs.writeFileSync(log,'Print mode: conversation='+id+', sending message');if(prompt==='NATURALRACE')fs.writeFileSync(${JSON.stringify(raceReadyFile)},'ready');setTimeout(()=>{console.log('completed')},prompt==='NATURALRACE'?20:100);}\n`);await chmod(binary,0o755);
    await ensureSession(port,'pre-stop-session',profileId,home);const beforeArgs=await readFile(argsFile,'utf8').catch(()=>'');assert.equal((await post(port,'/sessions/pre-stop-session/turns',turnBody(profileId,home,'PRESTOP'))).status,200);const preStopped=await post(port,'/sessions/pre-stop-session/stop',{});assert.equal(preStopped.body.processExited,true);assert.equal(await readFile(argsFile,'utf8').catch(()=>''),beforeArgs,'stop-before-spawn must prevent agy execution');const preEvents=(await get(port,'/sessions/pre-stop-session/events?after=0&includeDeltas=1')).body.events;assert.equal(preEvents.filter(event=>event.event_type==='turn/interrupted').length,1);await assertReleased(port,'pre-stop-session');
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'spawn-race-session',profileId,home);assert.equal((await post(port,'/sessions/spawn-race-session/turns',turnBody(profileId,home,'SPAWNRACE'))).status,200);const racePids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))];const raceStopped=await post(port,'/sessions/spawn-race-session/stop',{});assert.equal(raceStopped.body.processExited,true);await assertProcessTreeGone(racePids);const raceEvents=(await get(port,'/sessions/spawn-race-session/events?after=0&includeDeltas=1')).body.events;assert.equal(raceEvents.filter(event=>event.event_type==='turn/interrupted').length,1);assert.equal(raceEvents.some(event=>['turn/completed','turn/failed'].includes(event.event_type)),false);
    const attachmentDir=path.join(data,'attachments','attachment-session'),attachmentPath=path.join(attachmentDir,'note.txt');await mkdir(attachmentDir,{recursive:true});await writeFile(attachmentPath,'verified attachment contents');
    await ensureSession(port,'attachment-session',profileId,home);const attachmentTurn={...turnBody(profileId,home,`read ${attachmentPath}`),attachments:[{id:'known',name:'note.txt',path:attachmentPath}]};assert.equal((await post(port,'/sessions/attachment-session/turns',attachmentTurn)).status,200);await waitTerminal(port,'attachment-session','turn/completed');assert.match(await readFile(argsFile,'utf8'),new RegExp(`--add-dir ${escapeRegex(attachmentDir)}`));assert.equal(await readFile(attachmentPath,'utf8'),'verified attachment contents');
    const otherDir=path.join(data,'attachments','other-session');await mkdir(otherDir,{recursive:true});const otherPath=path.join(otherDir,'secret.txt');await writeFile(otherPath,'must not be read');await ensureSession(port,'forged-attachment',profileId,home);assert.equal((await post(port,'/sessions/forged-attachment/turns',{...turnBody(profileId,home,'forged'),attachments:[{id:'forged',path:otherPath}]})).status,200);await waitTerminal(port,'forged-attachment','turn/failed');await assertReleased(port,'forged-attachment');
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'stop-session',profileId,home);
    assert.equal((await post(port,'/sessions/stop-session/turns',turnBody(profileId,home,'STOP'))).status,200);
    const stopPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))],started=Date.now(),stopped=await post(port,'/sessions/stop-session/stop',{});assert.equal(stopped.status,200);assert.equal(stopped.body.processExited,true);assert.ok(Date.now()-started>=100,'SIGTERM grace period should elapse before SIGKILL');
    await assertProcessTreeGone(stopPids);
    const events=(await get(port,'/sessions/stop-session/events?after=0&includeDeltas=1')).body.events;assert.equal(events.filter(event=>event.event_type==='turn/interrupted').length,1);assert.equal(events.some(event=>['turn/completed','turn/failed'].includes(event.event_type)),false);await assertReleased(port,'stop-session');
    await rm(raceReadyFile,{force:true});await ensureSession(port,'natural-race-session',profileId,home);assert.equal((await post(port,'/sessions/natural-race-session/turns',turnBody(profileId,home,'NATURALRACE'))).status,200);await waitFile(raceReadyFile);await post(port,'/sessions/natural-race-session/stop',{});const naturalEvents=await waitAnyTerminal(port,'natural-race-session');assert.equal(naturalEvents.filter(event=>['turn/completed','turn/failed','turn/interrupted'].includes(event.event_type)).length,1);
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'drain-session',profileId,home);assert.equal((await post(port,'/sessions/drain-session/turns',turnBody(profileId,home,'DRAIN'))).status,200);const drainPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))];assert.equal((await post(port,'/drain/start',{ttlMs:500})).status,200);assert.equal((await post(port,'/drain/cancel',{})).status,200);for(const processId of drainPids)assert.doesNotThrow(()=>process.kill(processId,0),'cancelling deploy drain must not terminate active work');await post(port,'/sessions/drain-session/stop',{});await assertProcessTreeGone(drainPids);
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'timeout-session',profileId,home);assert.equal((await post(port,'/sessions/timeout-session/turns',turnBody(profileId,home,'TIMEOUT'))).status,200);const timeoutPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))];await waitTerminal(port,'timeout-session','turn/failed');await assertProcessTreeGone(timeoutPids);const timeoutEvents=(await get(port,'/sessions/timeout-session/events?after=0&includeDeltas=1')).body.events;assert.equal(timeoutEvents.filter(event=>['turn/completed','turn/failed','turn/interrupted'].includes(event.event_type)).length,1);await assertReleased(port,'timeout-session');
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'shutdown-session',profileId,home);assert.equal((await post(port,'/sessions/shutdown-session/turns',turnBody(profileId,home,'SHUTDOWN'))).status,200);const shutdownPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))];child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));await assertProcessTreeGone(shutdownPids);const shutdownDb=new Database(path.join(data,'runtime.sqlite3'),{readonly:true});const shutdownTerminal=shutdownDb.prepare("SELECT event_type FROM events WHERE session_id='shutdown-session' AND event_type IN ('turn/completed','turn/failed','turn/interrupted') ORDER BY sequence").all();const shutdownSession=shutdownDb.prepare("SELECT status,active_turn_id,interruption_reason FROM sessions WHERE id='shutdown-session'").get();shutdownDb.close();assert.deepEqual(shutdownTerminal,[{event_type:'turn/interrupted'}]);assert.equal(shutdownSession.active_turn_id,null);assert.equal(shutdownSession.status,'interrupted');assert.equal(shutdownSession.interruption_reason,'runtime_shutdown');
  }finally{if(child.exitCode===null)child.kill('SIGTERM');await new Promise(resolve=>child.exitCode===null?child.once('exit',resolve):resolve());await rm(root,{recursive:true,force:true});}
});

function turnBody(id,home,text){return{profile:{id,homeDir:home},accountId:id,text,input:[{type:'text',text}],turnId:`turn-${text.replaceAll(' ','-')}`,clientMessageId:`message-${text.replaceAll(' ','-')}`,permissionMode:'workspace-write'};}
async function ensureSession(port,sessionId,id,home){const response=await post(port,'/antigravity/sessions',{sessionId,profile:{id,homeDir:home},accountId:id,cwd:process.cwd(),title:sessionId,mode:'workspace-write'});assert.equal(response.status,200);}
async function assertReleased(port,id){const session=(await get(port,`/sessions/${id}`)).body.session;assert.equal(session.active_turn_id,null);assert.ok(['failed','interrupted'].includes(session.status));}
async function waitTerminal(port,id,type){return waitTerminalCount(port,id,type,1);}
async function waitAnyTerminal(port,id){const end=Date.now()+10000;while(Date.now()<end){const events=(await get(port,`/sessions/${id}/events?after=0&includeDeltas=1`)).body.events;if(events.some(event=>['turn/completed','turn/failed','turn/interrupted'].includes(event.event_type)))return events;await delay(20);}throw new Error('terminal event was not persisted');}
async function waitTerminalCount(port,id,type,count){const end=Date.now()+10000;let events=[];while(Date.now()<end){events=(await get(port,`/sessions/${id}/events?after=0&includeDeltas=1`)).body.events;if(events.filter(event=>event.event_type===type).length>=count)return events;await delay(30);}throw new Error(`${type} was not persisted: ${JSON.stringify(events)}`);}
async function waitFile(file){const end=Date.now()+10000;while(Date.now()<end){const value=await readFile(file,'utf8').catch(()=>'');if(value)return value;await delay(20);}throw new Error(`${path.basename(file)} was not written`);}
async function clearPidFiles(...files){await Promise.all(files.map(file=>rm(file,{force:true})));}
async function assertProcessTreeGone(pids){await delay(30);for(const pid of pids){assert.ok(Number.isInteger(pid)&&pid>1);assert.throws(()=>process.kill(pid,0),error=>error?.code==='ESRCH',`process ${pid} is still alive`);}}
async function get(port,url){const response=await fetch(`http://127.0.0.1:${port}${url}`);return{status:response.status,body:await response.json()};}
async function post(port,url,body){const response=await fetch(`http://127.0.0.1:${port}${url}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return{status:response.status,body:await response.json()};}
async function waitHttp(port,url,child,output){const end=Date.now()+10000;while(Date.now()<end){if(child.exitCode!==null)throw new Error(`runtime exited\n${output.join('')}`);try{if((await fetch(`http://127.0.0.1:${port}${url}`)).ok)return;}catch{}await delay(30);}throw new Error(`runtime unavailable\n${output.join('')}`);}
function freePort(){return new Promise((resolve,reject)=>{const server=net.createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();server.close(()=>resolve(address.port));});});}
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const escapeRegex=value=>String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
