import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { chmod, mkdir, mkdtemp, readFile, readdir, rm, stat, unlink, writeFile } from 'node:fs/promises';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import Database from 'better-sqlite3';

test('Antigravity Runtime releases failed claims and waits through SIGKILL cancellation',async()=>{
  const port=await freePort(),root=await mkdtemp(path.join(os.tmpdir(),'agentdeck-agy-runtime-')),data=path.join(root,'data'),profileId='abcdef0123456789',home=path.join(data,'antigravity-profiles',profileId,'home'),binary=path.join(root,'agy'),pidFile=path.join(root,'agy.pid'),childPidFile=path.join(root,'agy-child.pid'),grandPidFile=path.join(root,'agy-grand.pid'),raceReadyFile=path.join(root,'race-ready'),argsFile=path.join(root,'args');
  await mkdir(home,{recursive:true});
  const env={...process.env,NODE_ENV:'test',DATA_DIR:data,RUNTIME_DATA_DIR:data,RUNTIME_DB:path.join(data,'runtime.sqlite3'),RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(port),SKIP_RUNTIME_BOOTSTRAP:'1',ANTIGRAVITY_BIN:binary,ANTIGRAVITY_STOP_GRACE_MS:'120',ANTIGRAVITY_TURN_TIMEOUT_MS:'5000',ANTIGRAVITY_TEST_BEFORE_SPAWN_DELAY_MS:'100',ANTIGRAVITY_TEST_AFTER_SPAWN_DELAY_MS:'100',RUNTIME_DRAIN_TIMEOUT_MS:'150',HOME:path.join(root,'empty-home'),PATH:`${path.dirname(process.execPath)}:/usr/bin:/bin`};
  const child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env,stdio:['ignore','pipe','pipe']}),output=[];child.stdout.on('data',x=>output.push(String(x)));child.stderr.on('data',x=>output.push(String(x)));
  try{
    await waitHttp(port,'/healthz',child,output);
    await mkdir(path.join(data,'runtime'),{recursive:true});
    await writeFile(path.join(data,'runtime','antigravity-logs'),'blocks log directory');
    await ensureSession(port,'log-failure',profileId,home);
    assert.equal((await post(port,'/sessions/log-failure/turns',turnBody(profileId,home,'log failure'))).status,200);
    await waitTerminal(port,'log-failure','turn/failed');await assertReleased(port,'log-failure');
    await unlink(path.join(data,'runtime','antigravity-logs'));

    await ensureSession(port,'binary-failure',profileId,home);
    assert.equal((await post(port,'/sessions/binary-failure/turns',turnBody(profileId,home,'missing binary'))).status,200);
    await waitTerminal(port,'binary-failure','turn/failed');await assertReleased(port,'binary-failure');
    const retry=await post(port,'/sessions/binary-failure/turns',{...turnBody(profileId,home,'missing binary retry'),turnId:'retry-turn',clientMessageId:'retry-message'});assert.equal(retry.status,200,'a pre-spawn failure must not permanently retain the claim');
    await waitTerminalCount(port,'binary-failure','turn/failed',2);await assertReleased(port,'binary-failure');

    await writeFile(binary,`#!/usr/bin/env node\nimport fs from 'node:fs';import path from 'node:path';import{spawn}from'node:child_process';\nconst args=process.argv.slice(2),prompt=args.at(-1)||'',log=args[args.indexOf('--log-file')+1];fs.appendFileSync(${JSON.stringify(argsFile)},args.join(' ')+'\\n');\nif(['STOP','SPAWNRACE','TIMEOUT','SHUTDOWN','DRAIN','LEADEREXIT','COMPLETEORPHAN'].includes(prompt)){fs.writeFileSync(${JSON.stringify(pidFile)},String(process.pid));const c=spawn('/bin/sh',['-c',\"trap '' TERM; sleep 1000 & echo $! > \\\"$GRAND_PID_FILE\\\"; wait\"],{stdio:'ignore',env:{...process.env,GRAND_PID_FILE:${JSON.stringify(grandPidFile)}}});fs.writeFileSync(${JSON.stringify(childPidFile)},String(c.pid));if(prompt==='COMPLETEORPHAN'){const id='ce69f19b-3085-4abf-b514-03b7e4d0813a',dir=path.join(process.env.HOME,'.gemini','antigravity-cli','conversations');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.db'),'');fs.writeFileSync(log,'Print mode: conversation='+id+', sending message');console.log('completed with descendant');c.unref();}else{if(prompt!=='LEADEREXIT')process.on('SIGTERM',()=>{});setInterval(()=>{},1000);}}else{const id='ce69f19b-3085-4abf-b514-03b7e4d0813a',dir=path.join(process.env.HOME,'.gemini','antigravity-cli','conversations');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.db'),'');fs.writeFileSync(log,'Print mode: conversation='+id+', sending message');if(prompt==='NATURALRACE')fs.writeFileSync(${JSON.stringify(raceReadyFile)},'ready');setTimeout(()=>{console.log('completed')},prompt==='NATURALRACE'?20:100);}\n`);await chmod(binary,0o755);
    const missingCwd=path.join(root,'missing-spawn-cwd');await ensureSession(port,'async-spawn-error',profileId,home,missingCwd);assert.equal((await post(port,'/sessions/async-spawn-error/turns',turnBody(profileId,home,'async spawn error'))).status,200);const spawnFailureEvents=await waitTerminal(port,'async-spawn-error','turn/failed');assert.equal(spawnFailureEvents.filter(event=>event.event_type==='turn/failed').length,1);await assertReleased(port,'async-spawn-error');const spawnFailureStop=await post(port,'/sessions/async-spawn-error/stop',{});assert.equal(spawnFailureStop.body.alreadyFailed,true);assert.equal((await readdir(path.join(data,'runtime','antigravity-terminal-intents')).catch(()=>[])).filter(name=>name.endsWith('.json')).length,0);const spawnDb=new Database(path.join(data,'runtime.sqlite3'),{readonly:true});assert.equal(spawnDb.prepare("SELECT COUNT(*) FROM antigravity_terminal_intents WHERE session_id='async-spawn-error'").pluck().get(),0);spawnDb.close();await ensureSession(port,'async-spawn-error',profileId,home,process.cwd());assert.equal((await post(port,'/sessions/async-spawn-error/turns',{...turnBody(profileId,home,'spawn retry'),turnId:'turn-spawn-retry',clientMessageId:'message-spawn-retry'})).status,200);await waitTerminal(port,'async-spawn-error','turn/completed');
    await ensureSession(port,'pre-stop-session',profileId,home);const beforeArgs=await readFile(argsFile,'utf8').catch(()=>'');assert.equal((await post(port,'/sessions/pre-stop-session/turns',turnBody(profileId,home,'PRESTOP'))).status,200);const preStopped=await post(port,'/sessions/pre-stop-session/stop',{});assert.equal(preStopped.body.processExited,true);assert.equal(await readFile(argsFile,'utf8').catch(()=>''),beforeArgs,'stop-before-spawn must prevent agy execution');const preEvents=(await get(port,'/sessions/pre-stop-session/events?after=0&includeDeltas=1')).body.events;assert.equal(preEvents.filter(event=>event.event_type==='turn/interrupted').length,1);await assertReleased(port,'pre-stop-session');
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'spawn-race-session',profileId,home);assert.equal((await post(port,'/sessions/spawn-race-session/turns',turnBody(profileId,home,'SPAWNRACE'))).status,200);const racePids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))];const raceStopped=await post(port,'/sessions/spawn-race-session/stop',{});assert.equal(raceStopped.body.processExited,true);await assertProcessTreeGone(racePids);const raceEvents=(await get(port,'/sessions/spawn-race-session/events?after=0&includeDeltas=1')).body.events;assert.equal(raceEvents.filter(event=>event.event_type==='turn/interrupted').length,1);assert.equal(raceEvents.some(event=>['turn/completed','turn/failed'].includes(event.event_type)),false);
    const attachmentDir=path.join(data,'attachments','attachment-session'),attachmentPath=path.join(attachmentDir,'note.txt');await mkdir(attachmentDir,{recursive:true});await writeFile(attachmentPath,'verified attachment contents');
    await ensureSession(port,'attachment-session',profileId,home);const attachmentTurn={...turnBody(profileId,home,`read ${attachmentPath}`),attachments:[{id:'known',name:'note.txt',path:attachmentPath}]};assert.equal((await post(port,'/sessions/attachment-session/turns',attachmentTurn)).status,200);await waitTerminal(port,'attachment-session','turn/completed');assert.match(await readFile(argsFile,'utf8'),new RegExp(`--add-dir ${escapeRegex(attachmentDir)}`));assert.equal(await readFile(attachmentPath,'utf8'),'verified attachment contents');
    const otherDir=path.join(data,'attachments','other-session');await mkdir(otherDir,{recursive:true});const otherPath=path.join(otherDir,'secret.txt');await writeFile(otherPath,'must not be read');await ensureSession(port,'forged-attachment',profileId,home);assert.equal((await post(port,'/sessions/forged-attachment/turns',{...turnBody(profileId,home,'forged'),attachments:[{id:'forged',path:otherPath}]})).status,200);await waitTerminal(port,'forged-attachment','turn/failed');await assertReleased(port,'forged-attachment');
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'stop-session',profileId,home);
    assert.equal((await post(port,'/sessions/stop-session/turns',turnBody(profileId,home,'STOP'))).status,200);
    const stopPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))],started=Date.now(),stopped=await post(port,'/sessions/stop-session/stop',{});assert.equal(stopped.status,200);assert.equal(stopped.body.processExited,true);assert.ok(Date.now()-started>=100,'SIGTERM grace period should elapse before SIGKILL');
    await assertProcessTreeGone(stopPids);
    const events=(await get(port,'/sessions/stop-session/events?after=0&includeDeltas=1')).body.events;assert.equal(events.filter(event=>event.event_type==='turn/interrupted').length,1);assert.equal(events.some(event=>['turn/completed','turn/failed'].includes(event.event_type)),false);await assertReleased(port,'stop-session');
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'leader-exit-session',profileId,home);assert.equal((await post(port,'/sessions/leader-exit-session/turns',turnBody(profileId,home,'LEADEREXIT'))).status,200);const leaderExitPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))],leaderPgid=leaderExitPids[0],leaderStarted=Date.now(),leaderStopped=await post(port,'/sessions/leader-exit-session/stop',{});assert.equal(leaderStopped.status,200);assert.equal(leaderStopped.body.processExited,true);assert.ok(Date.now()-leaderStarted>=100,'leader close must not bypass process-group grace');await assertProcessTreeGone(leaderExitPids);assert.throws(()=>process.kill(-leaderPgid,0),error=>error?.code==='ESRCH');const leaderEvents=(await get(port,'/sessions/leader-exit-session/events?after=0&includeDeltas=1')).body.events;assert.equal(leaderEvents.filter(event=>event.event_type==='turn/interrupted').length,1);
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'completed-orphan-session',profileId,home);const completedOrphanStarted=Date.now();assert.equal((await post(port,'/sessions/completed-orphan-session/turns',turnBody(profileId,home,'COMPLETEORPHAN'))).status,200);const completedOrphanPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))],completedOrphanPgid=completedOrphanPids[0],completedOrphanEvents=await waitTerminal(port,'completed-orphan-session','turn/completed');assert.ok(Date.now()-completedOrphanStarted>=100,'completed must wait for the descendant process-group grace');await assertProcessTreeGone(completedOrphanPids);assert.throws(()=>process.kill(-completedOrphanPgid,0),error=>error?.code==='ESRCH');assert.equal(completedOrphanEvents.filter(event=>event.event_type==='item/completed').length,1);assert.equal(completedOrphanEvents.filter(event=>event.event_type==='turn/completed').length,1);assert.equal(completedOrphanEvents.some(event=>['turn/failed','turn/interrupted'].includes(event.event_type)),false);
    await rm(raceReadyFile,{force:true});await ensureSession(port,'natural-race-session',profileId,home);assert.equal((await post(port,'/sessions/natural-race-session/turns',turnBody(profileId,home,'NATURALRACE'))).status,200);await waitFile(raceReadyFile);await post(port,'/sessions/natural-race-session/stop',{});const naturalEvents=await waitAnyTerminal(port,'natural-race-session');assert.equal(naturalEvents.filter(event=>['turn/completed','turn/failed','turn/interrupted'].includes(event.event_type)).length,1);
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'drain-session',profileId,home);assert.equal((await post(port,'/sessions/drain-session/turns',turnBody(profileId,home,'DRAIN'))).status,200);const drainPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))];assert.equal((await post(port,'/drain/start',{ttlMs:500})).status,200);assert.equal((await post(port,'/drain/cancel',{})).status,200);for(const processId of drainPids)assert.doesNotThrow(()=>process.kill(processId,0),'cancelling deploy drain must not terminate active work');await post(port,'/sessions/drain-session/stop',{});await assertProcessTreeGone(drainPids);
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'timeout-session',profileId,home);assert.equal((await post(port,'/sessions/timeout-session/turns',turnBody(profileId,home,'TIMEOUT'))).status,200);const timeoutPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))];await waitTerminal(port,'timeout-session','turn/failed');await assertProcessTreeGone(timeoutPids);const timeoutEvents=(await get(port,'/sessions/timeout-session/events?after=0&includeDeltas=1')).body.events;assert.equal(timeoutEvents.filter(event=>['turn/completed','turn/failed','turn/interrupted'].includes(event.event_type)).length,1);await assertReleased(port,'timeout-session');
    await clearPidFiles(pidFile,childPidFile,grandPidFile);await ensureSession(port,'shutdown-session',profileId,home);assert.equal((await post(port,'/sessions/shutdown-session/turns',turnBody(profileId,home,'SHUTDOWN'))).status,200);const shutdownPids=[Number(await waitFile(pidFile)),Number(await waitFile(childPidFile)),Number(await waitFile(grandPidFile))];child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));await assertProcessTreeGone(shutdownPids);const shutdownDb=new Database(path.join(data,'runtime.sqlite3'),{readonly:true});const shutdownTerminal=shutdownDb.prepare("SELECT event_type FROM events WHERE session_id='shutdown-session' AND event_type IN ('turn/completed','turn/failed','turn/interrupted') ORDER BY sequence").all();const shutdownSession=shutdownDb.prepare("SELECT status,active_turn_id,interruption_reason FROM sessions WHERE id='shutdown-session'").get();shutdownDb.close();assert.deepEqual(shutdownTerminal,[{event_type:'turn/interrupted'}]);assert.equal(shutdownSession.active_turn_id,null);assert.equal(shutdownSession.status,'interrupted');assert.equal(shutdownSession.interruption_reason,'runtime_shutdown');
  }finally{if(child.exitCode===null)child.kill('SIGTERM');await new Promise(resolve=>child.exitCode===null?child.once('exit',resolve):resolve());await rm(root,{recursive:true,force:true});}
});

test('Antigravity process-group cleanup failure is durable and retryable',async()=>{
  const port=await freePort(),root=await mkdtemp(path.join(os.tmpdir(),'agentdeck-agy-cleanup-retry-')),data=path.join(root,'data'),dbFile=path.join(data,'runtime.sqlite3'),profileId='abcdef0123456789',home=path.join(data,'antigravity-profiles',profileId,'home'),binary=path.join(root,'agy'),pidFile=path.join(root,'pid'),output=[];await mkdir(home,{recursive:true});
  await writeFile(binary,`#!/usr/bin/env node\nimport fs from'node:fs';import path from'node:path';import{spawn}from'node:child_process';const args=process.argv.slice(2),log=args[args.indexOf('--log-file')+1],id='ce69f19b-3085-4abf-b514-03b7e4d0813a',dir=path.join(process.env.HOME,'.gemini','antigravity-cli','conversations');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.db'),'');fs.writeFileSync(log,'Print mode: conversation='+id+', sending message');fs.writeFileSync(${JSON.stringify(pidFile)},String(process.pid));const child=spawn('/bin/sh',['-c',"trap '' TERM; sleep 1000"],{stdio:'ignore'});child.unref();console.log('answer before cleanup failure');`);await chmod(binary,0o755);
  const env={...process.env,NODE_ENV:'test',DATA_DIR:data,RUNTIME_DATA_DIR:data,RUNTIME_DB:dbFile,RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(port),SKIP_RUNTIME_BOOTSTRAP:'1',ANTIGRAVITY_BIN:binary,ANTIGRAVITY_STOP_GRACE_MS:'60',ANTIGRAVITY_KILL_CONFIRM_MS:'500',ANTIGRAVITY_TEST_CLEANUP_FAILURES:'1',HOME:path.join(root,'empty-home'),PATH:`${path.dirname(process.execPath)}:/usr/bin:/bin`};const child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env,stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>output.push(String(x)));child.stderr.on('data',x=>output.push(String(x)));
  try{await waitHttp(port,'/healthz',child,output);await ensureSession(port,'cleanup-retry',profileId,home);await post(port,'/sessions/cleanup-retry/turns',turnBody(profileId,home,'cleanup retry'));await waitFileCount(path.join(data,'runtime','antigravity-terminal-intents'),1);await waitDb(dbFile,db=>{const intent=db.prepare("SELECT terminal,reason,cleanup_required,cleanup_attempts,cleanup_error,process_group_id FROM antigravity_terminal_intents WHERE session_id='cleanup-retry'").get(),session=db.prepare("SELECT active_turn_id FROM sessions WHERE id='cleanup-retry'").get();return intent?.terminal==='failed'&&intent.reason==='antigravity_process_group_cleanup_failed'&&intent.cleanup_required===1&&intent.cleanup_attempts>=1&&intent.cleanup_error&&intent.process_group_id>1&&session?.active_turn_id;});const firstEvents=(await get(port,'/sessions/cleanup-retry/events?after=0&includeDeltas=1')).body.events;assert.equal(firstEvents.some(event=>event.event_type==='turn/completed'),false);const retried=await post(port,'/sessions/cleanup-retry/stop',{});assert.equal(retried.status,200);assert.equal(retried.body.alreadyFailed,true);const events=await waitTerminal(port,'cleanup-retry','turn/failed');assert.equal(events.filter(event=>event.event_type==='turn/failed').length,1);await assertReleased(port,'cleanup-retry');const db=new Database(dbFile,{readonly:true});assert.equal(db.prepare("SELECT COUNT(*) FROM antigravity_terminal_intents WHERE session_id='cleanup-retry'").pluck().get(),0);db.close();assert.equal((await readdir(path.join(data,'runtime','antigravity-terminal-intents'))).filter(name=>name.endsWith('.json')).length,0);
  }finally{if(child.exitCode===null)child.kill('SIGTERM');await new Promise(resolve=>child.exitCode===null?child.once('exit',resolve):resolve());await rm(root,{recursive:true,force:true});}
});

test('Antigravity bootstrap verifies surviving descendants after the leader exits',async()=>{
  const port=await freePort(),root=await mkdtemp(path.join(os.tmpdir(),'agentdeck-agy-descendant-recovery-')),data=path.join(root,'data'),dbFile=path.join(data,'runtime.sqlite3'),profileId='abcdef0123456789',home=path.join(data,'antigravity-profiles',profileId,'home'),binary=path.join(root,'agy'),leaderFile=path.join(root,'leader.pid'),childFile=path.join(root,'child.pid'),grandFile=path.join(root,'grand.pid'),output=[];await mkdir(home,{recursive:true});
  await writeFile(binary,`#!/usr/bin/env node\nimport fs from'node:fs';import path from'node:path';import{spawn}from'node:child_process';const args=process.argv.slice(2),log=args[args.indexOf('--log-file')+1],id='ce69f19b-3085-4abf-b514-03b7e4d0813a',dir=path.join(process.env.HOME,'.gemini','antigravity-cli','conversations');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.db'),'');fs.writeFileSync(log,'Print mode: conversation='+id+', sending message');fs.writeFileSync(${JSON.stringify(leaderFile)},String(process.pid));const child=spawn('/bin/sh',['-c',${JSON.stringify(`trap '' TERM; sleep 1000 & echo $! > "${grandFile}"; wait`)}],{stdio:'ignore'});fs.writeFileSync(${JSON.stringify(childFile)},String(child.pid));child.unref();console.log('answer before descendant recovery');`);await chmod(binary,0o755);
  const base={...process.env,NODE_ENV:'test',DATA_DIR:data,RUNTIME_DATA_DIR:data,RUNTIME_DB:dbFile,RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(port),ANTIGRAVITY_BIN:binary,ANTIGRAVITY_STOP_GRACE_MS:'80',ANTIGRAVITY_KILL_CONFIRM_MS:'1000',HOME:path.join(root,'empty-home'),PATH:`${path.dirname(process.execPath)}:/usr/bin:/bin`};let runtime=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env:{...base,SKIP_RUNTIME_BOOTSTRAP:'1',ANTIGRAVITY_TEST_CLEANUP_PRE_SIGNAL_FAILURES:'1'},stdio:['ignore','pipe','pipe']});runtime.stdout.on('data',x=>output.push(String(x)));runtime.stderr.on('data',x=>output.push(String(x)));
  try{await waitHttp(port,'/healthz',runtime,output);await ensureSession(port,'descendant-recovery',profileId,home);await post(port,'/sessions/descendant-recovery/turns',turnBody(profileId,home,'descendant recovery'));const leader=Number(await waitFile(leaderFile)),child=Number(await waitFile(childFile)),grand=Number(await waitFile(grandFile));await waitDb(dbFile,db=>{const intent=db.prepare("SELECT terminal,reason,cleanup_required,process_group_members_json FROM antigravity_terminal_intents WHERE session_id='descendant-recovery'").get();if(!intent?.process_group_members_json)return false;const members=JSON.parse(intent.process_group_members_json);return intent.terminal==='failed'&&intent.reason==='antigravity_process_group_cleanup_failed'&&intent.cleanup_required===1&&members.some(member=>member.pid===child)&&members.some(member=>member.pid===grand);});await waitPidGone(leader);assert.doesNotThrow(()=>process.kill(child,0));assert.doesNotThrow(()=>process.kill(grand,0));runtime.kill('SIGKILL');await new Promise(resolve=>runtime.once('exit',resolve));runtime=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env:base,stdio:['ignore','pipe','pipe']});runtime.stdout.on('data',x=>output.push(String(x)));runtime.stderr.on('data',x=>output.push(String(x)));await waitHttp(port,'/readyz',runtime,output);await assertProcessTreeGone([child,grand]);const events=await waitTerminal(port,'descendant-recovery','turn/failed');assert.equal(events.filter(event=>event.event_type==='turn/failed').length,1);assert.equal(events.some(event=>event.event_type==='turn/completed'),false);await assertReleased(port,'descendant-recovery');let db=new Database(dbFile,{readonly:true});assert.equal(db.prepare("SELECT COUNT(*) FROM antigravity_terminal_intents WHERE session_id='descendant-recovery'").pluck().get(),0);db.close();assert.equal((await readdir(path.join(data,'runtime','antigravity-terminal-intents')).catch(()=>[])).filter(name=>name.endsWith('.json')).length,0);
    await ensureSession(port,'identity-mismatch',profileId,home);runtime.kill('SIGTERM');await new Promise(resolve=>runtime.once('exit',resolve));const sentinel=spawn('/bin/sh',['-c',"trap '' TERM; sleep 1000"],{detached:true,stdio:'ignore'});assert.ok(sentinel.pid&&sentinel.pid>1);sentinel.unref();db=new Database(dbFile);const terminalPayload=JSON.stringify({method:'turn/failed',turnId:'turn-mismatch',params:{turn:{id:'turn-mismatch',status:'failed'}}}),members=JSON.stringify([{pid:sentinel.pid,startTicks:'1',pgrp:sentinel.pid,sessionId:sentinel.pid}]);db.prepare("UPDATE sessions SET status='running',active_turn_id='turn-mismatch' WHERE id='identity-mismatch'").run();db.prepare("INSERT INTO antigravity_terminal_intents(session_id,turn_id,terminal,reason,client_message_id,assistant_item_json,terminal_payload_json,created_at,updated_at,last_error,cleanup_required,process_group_id,process_group_leader_pid,process_group_start_ticks,process_group_members_json,cleanup_attempts,cleanup_error) VALUES('identity-mismatch','turn-mismatch','failed','antigravity_process_group_cleanup_failed','message-mismatch',NULL,?,?,?,NULL,1,?,?,?, ?,0,NULL)").run(terminalPayload,Date.now(),Date.now(),sentinel.pid,sentinel.pid+100000,'1',members);db.close();runtime=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env:base,stdio:['ignore','pipe','pipe']});runtime.stdout.on('data',x=>output.push(String(x)));runtime.stderr.on('data',x=>output.push(String(x)));const exitCode=await new Promise(resolve=>runtime.once('exit',resolve));assert.notEqual(exitCode,0);assert.doesNotThrow(()=>process.kill(sentinel.pid,0),'identity mismatch must not signal an unrelated process group');try{process.kill(-sentinel.pid,'SIGKILL')}catch{}await waitPidGone(sentinel.pid);
  }finally{if(runtime.exitCode===null)runtime.kill('SIGTERM');await new Promise(resolve=>runtime.exitCode===null?runtime.once('exit',resolve):resolve());for(const file of[childFile,grandFile]){const pid=Number(await readFile(file,'utf8').catch(()=>0));if(pid>1)try{process.kill(pid,'SIGKILL')}catch{}}await rm(root,{recursive:true,force:true});}
});

test('Antigravity terminal arbitration makes stop reflect the durable winner',async()=>{
  const port=await freePort(),root=await mkdtemp(path.join(os.tmpdir(),'agentdeck-agy-race-')),data=path.join(root,'data'),profileId='abcdef0123456789',home=path.join(data,'antigravity-profiles',profileId,'home'),binary=path.join(root,'agy'),afterClose=path.join(root,'after-close'),afterDecision=path.join(root,'after-decision'),output=[];
  await mkdir(home,{recursive:true});await writeFile(binary,`#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';const args=process.argv.slice(2),log=args[args.indexOf('--log-file')+1],id='ce69f19b-3085-4abf-b514-03b7e4d0813a',dir=path.join(process.env.HOME,'.gemini','antigravity-cli','conversations');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.db'),'');fs.writeFileSync(log,'Print mode: conversation='+id+', sending message');console.log('durable answer');`);await chmod(binary,0o755);
  const env={...process.env,NODE_ENV:'test',DATA_DIR:data,RUNTIME_DATA_DIR:data,RUNTIME_DB:path.join(data,'runtime.sqlite3'),RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(port),SKIP_RUNTIME_BOOTSTRAP:'1',ANTIGRAVITY_BIN:binary,ANTIGRAVITY_TEST_AFTER_CHILD_CLOSE_DELAY_MS:'500',ANTIGRAVITY_TEST_AFTER_CHILD_CLOSE_DELAY_MS_MARKER:afterClose,ANTIGRAVITY_TEST_AFTER_TERMINAL_DECISION_DELAY_MS:'500',ANTIGRAVITY_TEST_AFTER_TERMINAL_DECISION_DELAY_MS_MARKER:afterDecision,HOME:path.join(root,'empty-home'),PATH:`${path.dirname(process.execPath)}:/usr/bin:/bin`};
  const child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env,stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>output.push(String(x)));child.stderr.on('data',x=>output.push(String(x)));
  try{
    await waitHttp(port,'/healthz',child,output);await ensureSession(port,'stop-wins',profileId,home);await post(port,'/sessions/stop-wins/turns',turnBody(profileId,home,'stop wins'));await waitFile(afterClose);const stopped=await post(port,'/sessions/stop-wins/stop',{});assert.equal(stopped.status,200);assert.equal(stopped.body.interrupted,true);const stoppedEvents=await waitAnyTerminal(port,'stop-wins');assert.deepEqual(stoppedEvents.filter(e=>e.event_type.startsWith('turn/')).map(e=>e.event_type),['turn/start','turn/interrupted']);await assertReleased(port,'stop-wins');
    await rm(afterClose,{force:true});await rm(afterDecision,{force:true});await ensureSession(port,'complete-wins',profileId,home);await post(port,'/sessions/complete-wins/turns',turnBody(profileId,home,'complete wins'));await waitFile(afterDecision);const completedStop=await post(port,'/sessions/complete-wins/stop',{});assert.equal(completedStop.status,200);assert.equal(completedStop.body.interrupted,false);assert.equal(completedStop.body.alreadyCompleted,true);const completedEvents=await waitAnyTerminal(port,'complete-wins');assert.equal(completedEvents.filter(e=>e.event_type==='turn/completed').length,1);assert.equal(completedEvents.some(e=>e.event_type==='turn/interrupted'),false);
  }finally{if(child.exitCode===null)child.kill('SIGTERM');await new Promise(resolve=>child.exitCode===null?child.once('exit',resolve):resolve());await rm(root,{recursive:true,force:true});}
});

test('Antigravity terminal persistence failure retains the claim until a durable retry succeeds',async()=>{
  const port=await freePort(),root=await mkdtemp(path.join(os.tmpdir(),'agentdeck-agy-persist-')),data=path.join(root,'data'),profileId='abcdef0123456789',home=path.join(data,'antigravity-profiles',profileId,'home'),binary=path.join(root,'agy'),decision=path.join(root,'decision'),output=[];
  await mkdir(home,{recursive:true});await writeFile(binary,`#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';const args=process.argv.slice(2),log=args[args.indexOf('--log-file')+1],id='ce69f19b-3085-4abf-b514-03b7e4d0813a',dir=path.join(process.env.HOME,'.gemini','antigravity-cli','conversations');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.db'),'');fs.writeFileSync(log,'Print mode: conversation='+id+', sending message');console.log('one final answer');`);await chmod(binary,0o755);
  const env={...process.env,NODE_ENV:'test',DATA_DIR:data,RUNTIME_DATA_DIR:data,RUNTIME_DB:path.join(data,'runtime.sqlite3'),RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(port),SKIP_RUNTIME_BOOTSTRAP:'1',ANTIGRAVITY_BIN:binary,ANTIGRAVITY_TEST_TERMINAL_INTENT_FAILURES:'3',ANTIGRAVITY_TEST_AFTER_TERMINAL_DECISION_DELAY_MS_MARKER:decision,HOME:path.join(root,'empty-home'),PATH:`${path.dirname(process.execPath)}:/usr/bin:/bin`};
  const child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env,stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>output.push(String(x)));child.stderr.on('data',x=>output.push(String(x)));
  try{
    await waitHttp(port,'/healthz',child,output);await ensureSession(port,'persist-failure',profileId,home);await post(port,'/sessions/persist-failure/turns',turnBody(profileId,home,'persist failure'));await waitFile(decision);await delay(100);
    for(let attempt=0;attempt<2;attempt++){const failed=await post(port,'/sessions/persist-failure/stop',{});assert.equal(failed.status,503);assert.equal(failed.body.finalizationCommitted,false);const snapshot=(await get(port,'/sessions/persist-failure')).body.session;assert.equal(snapshot.active_turn_id,'turn-persist-failure');const events=(await get(port,'/sessions/persist-failure/events?after=0&includeDeltas=1')).body.events;assert.equal(events.some(e=>['turn/completed','turn/failed','turn/interrupted'].includes(e.event_type)),false);const journalDir=path.join(data,'runtime','antigravity-terminal-intents'),journals=(await readdir(journalDir)).filter(name=>name.endsWith('.json'));assert.equal(journals.length,1);assert.equal((await stat(journalDir)).mode&0o777,0o700);assert.equal((await stat(path.join(journalDir,journals[0]))).mode&0o777,0o600);const journal=JSON.parse(await readFile(path.join(journalDir,journals[0]),'utf8'));assert.equal(journal.schemaVersion,3);assert.match(journal.checksum,/^[a-f0-9]{64}$/);}
    const recovered=await post(port,'/sessions/persist-failure/stop',{});assert.equal(recovered.status,200);assert.equal(recovered.body.alreadyCompleted,true);const events=await waitAnyTerminal(port,'persist-failure');assert.equal(events.filter(e=>e.event_type==='item/completed').length,1);assert.equal(events.filter(e=>e.event_type==='turn/completed').length,1);assert.equal((await get(port,'/sessions/persist-failure')).body.session.active_turn_id,null);
  }finally{if(child.exitCode===null)child.kill('SIGTERM');await new Promise(resolve=>child.exitCode===null?child.once('exit',resolve):resolve());await rm(root,{recursive:true,force:true});}
});

test('Runtime bootstrap completes a pending Antigravity terminal without duplicating the assistant',async()=>{
  const port=await freePort(),root=await mkdtemp(path.join(os.tmpdir(),'agentdeck-agy-bootstrap-')),data=path.join(root,'data'),dbFile=path.join(data,'runtime.sqlite3'),profileId='abcdef0123456789',home=path.join(data,'antigravity-profiles',profileId,'home'),binary=path.join(root,'agy'),output=[];await mkdir(home,{recursive:true});
  await writeFile(binary,`#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';const args=process.argv.slice(2),log=args[args.indexOf('--log-file')+1],id='ce69f19b-3085-4abf-b514-03b7e4d0813a',dir=path.join(process.env.HOME,'.gemini','antigravity-cli','conversations');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.db'),'');fs.writeFileSync(log,'Print mode: conversation='+id+', sending message');console.log('bootstrap answer');`);await chmod(binary,0o755);
  const base={...process.env,NODE_ENV:'test',DATA_DIR:data,RUNTIME_DATA_DIR:data,RUNTIME_DB:dbFile,RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(port),ANTIGRAVITY_BIN:binary,HOME:path.join(root,'empty-home'),PATH:`${path.dirname(process.execPath)}:/usr/bin:/bin`};let child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env:{...base,SKIP_RUNTIME_BOOTSTRAP:'1',ANTIGRAVITY_TEST_TERMINAL_INTENT_FAILURES:'100'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>output.push(String(x)));child.stderr.on('data',x=>output.push(String(x)));
  try{
    await waitHttp(port,'/healthz',child,output);await ensureSession(port,'bootstrap-pending',profileId,home);await post(port,'/sessions/bootstrap-pending/turns',turnBody(profileId,home,'bootstrap pending'));await waitFileCount(path.join(data,'runtime','antigravity-terminal-intents'),1);let db=new Database(dbFile,{readonly:true});assert.equal(db.prepare("SELECT COUNT(*) FROM antigravity_terminal_intents WHERE session_id='bootstrap-pending'").pluck().get(),0);assert.equal(db.prepare("SELECT COUNT(*) FROM events WHERE session_id='bootstrap-pending' AND event_type IN ('item/completed','turn/completed')").pluck().get(),0);assert.equal(db.prepare("SELECT active_turn_id FROM sessions WHERE id='bootstrap-pending'").pluck().get(),'turn-bootstrap-pending');db.close();
    child.kill('SIGKILL');await new Promise(resolve=>child.once('exit',resolve));child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env:base,stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>output.push(String(x)));child.stderr.on('data',x=>output.push(String(x)));await waitHttp(port,'/healthz',child,output);await waitTerminal(port,'bootstrap-pending','turn/completed');db=new Database(dbFile,{readonly:true});assert.equal(db.prepare("SELECT COUNT(*) FROM events WHERE session_id='bootstrap-pending' AND event_type='item/completed'").pluck().get(),1);assert.equal(db.prepare("SELECT COUNT(*) FROM events WHERE session_id='bootstrap-pending' AND event_type='turn/completed'").pluck().get(),1);assert.equal(db.prepare("SELECT active_turn_id FROM sessions WHERE id='bootstrap-pending'").pluck().get(),null);assert.equal(db.prepare("SELECT COUNT(*) FROM antigravity_terminal_intents WHERE session_id='bootstrap-pending'").pluck().get(),0);db.close();assert.equal((await readdir(path.join(data,'runtime','antigravity-terminal-intents'))).filter(name=>name.endsWith('.json')).length,0);
  }finally{if(child.exitCode===null)child.kill('SIGTERM');await new Promise(resolve=>child.exitCode===null?child.once('exit',resolve):resolve());await rm(root,{recursive:true,force:true});}
});

test('Runtime is not accepting before bootstrap and fails closed on corrupt terminal sidecars',async()=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'agentdeck-agy-ready-')),data=path.join(root,'data'),dbFile=path.join(data,'runtime.sqlite3'),port=await freePort(),output=[];
  const base={...process.env,NODE_ENV:'test',DATA_DIR:data,RUNTIME_DATA_DIR:data,RUNTIME_DB:dbFile,RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(port),ANTIGRAVITY_TEST_BOOTSTRAP_DELAY_MS:'400'};
  let child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env:base,stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>output.push(String(x)));child.stderr.on('data',x=>output.push(String(x)));
  try{
    await delay(100);
    await assert.rejects(fetch(`http://127.0.0.1:${port}/readyz`),'the Runtime must not listen before recovery completes');
    await waitHttp(port,'/readyz',child,output);
    child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));

    const journalDir=path.join(data,'runtime','antigravity-terminal-intents');await mkdir(journalDir,{recursive:true});await writeFile(path.join(journalDir,'corrupt.json'),'{not-json',{mode:0o600});
    const failedOutput=[];child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env:{...base,RUNTIME_PORT:String(await freePort()),ANTIGRAVITY_TEST_BOOTSTRAP_DELAY_MS:'0'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>failedOutput.push(String(x)));child.stderr.on('data',x=>failedOutput.push(String(x)));
    const [code]=await new Promise(resolve=>child.once('exit',(exitCode,signal)=>resolve([exitCode,signal])));assert.notEqual(code,0);assert.match(failedOutput.join(''),/bootstrap|sidecar|recovery/i);
  }finally{if(child.exitCode===null)child.kill('SIGTERM');await new Promise(resolve=>child.exitCode===null?child.once('exit',resolve):resolve());await rm(root,{recursive:true,force:true});}
});

test('Antigravity stop recovers a pending intent without a handle and rejects an orphaned active claim',async()=>{
  const port=await freePort(),root=await mkdtemp(path.join(os.tmpdir(),'agentdeck-agy-stop-recovery-')),data=path.join(root,'data'),dbFile=path.join(data,'runtime.sqlite3'),profileId='abcdef0123456789',home=path.join(data,'antigravity-profiles',profileId,'home'),output=[];await mkdir(home,{recursive:true});
  const env={...process.env,NODE_ENV:'test',DATA_DIR:data,RUNTIME_DATA_DIR:data,RUNTIME_DB:dbFile,RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(port),SKIP_RUNTIME_BOOTSTRAP:'1',RUNTIME_DRAIN_TIMEOUT_MS:'100',ANTIGRAVITY_TEST_TERMINAL_EVENT_FAILURES:'1'};
  const child=spawn(process.execPath,['server/dist/agentdeck-runtime.js'],{cwd:process.cwd(),env,stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>output.push(String(x)));child.stderr.on('data',x=>output.push(String(x)));
  try{
    await waitHttp(port,'/healthz',child,output);await ensureSession(port,'pending-without-handle',profileId,home);await ensureSession(port,'orphaned-claim',profileId,home);
    const db=new Database(dbFile),now=Date.now(),terminalPayload=JSON.stringify({method:'turn/completed',clientMessageId:'message-pending',params:{turn:{id:'turn-pending',status:'completed'}}});
    db.prepare("UPDATE sessions SET status='running',active_turn_id='turn-pending' WHERE id='pending-without-handle'").run();
    db.prepare(`INSERT INTO antigravity_terminal_intents(session_id,turn_id,terminal,reason,client_message_id,assistant_item_json,terminal_payload_json,created_at,updated_at,last_error) VALUES (?,?,?,?,?,?,?,?,?,NULL)`).run('pending-without-handle','turn-pending','completed',null,'message-pending',null,terminalPayload,now,now);
    db.prepare("UPDATE sessions SET status='running',active_turn_id='turn-orphaned' WHERE id='orphaned-claim'").run();db.close();
    const failed=await post(port,'/sessions/pending-without-handle/stop',{});assert.equal(failed.status,503);let check=new Database(dbFile,{readonly:true});assert.equal(check.prepare("SELECT active_turn_id FROM sessions WHERE id='pending-without-handle'").pluck().get(),'turn-pending');assert.equal(check.prepare("SELECT COUNT(*) FROM antigravity_terminal_intents WHERE session_id='pending-without-handle'").pluck().get(),1);check.close();
    const recovered=await post(port,'/sessions/pending-without-handle/stop',{});assert.equal(recovered.status,200);assert.equal(recovered.body.alreadyCompleted,true);check=new Database(dbFile,{readonly:true});assert.equal(check.prepare("SELECT active_turn_id FROM sessions WHERE id='pending-without-handle'").pluck().get(),null);assert.equal(check.prepare("SELECT COUNT(*) FROM events WHERE session_id='pending-without-handle' AND event_type='turn/completed'").pluck().get(),1);check.close();
    const orphaned=await post(port,'/sessions/orphaned-claim/stop',{});assert.equal(orphaned.status,409);assert.equal(orphaned.body.error,'antigravity_state_recovery_required');assert.equal(orphaned.body.alreadyStopped,undefined);
  }finally{if(child.exitCode===null)child.kill('SIGTERM');await new Promise(resolve=>child.exitCode===null?child.once('exit',resolve):resolve());await rm(root,{recursive:true,force:true});}
});

function turnBody(id,home,text){return{profile:{id,homeDir:home},accountId:id,text,input:[{type:'text',text}],turnId:`turn-${text.replaceAll(' ','-')}`,clientMessageId:`message-${text.replaceAll(' ','-')}`,permissionMode:'workspace-write'};}
async function ensureSession(port,sessionId,id,home,cwd=process.cwd()){const response=await post(port,'/antigravity/sessions',{sessionId,profile:{id,homeDir:home},accountId:id,cwd,title:sessionId,mode:'workspace-write'});assert.equal(response.status,200);}
async function assertReleased(port,id){const session=(await get(port,`/sessions/${id}`)).body.session;assert.equal(session.active_turn_id,null);assert.ok(['failed','interrupted'].includes(session.status));}
async function waitTerminal(port,id,type){return waitTerminalCount(port,id,type,1);}
async function waitAnyTerminal(port,id){const end=Date.now()+10000;while(Date.now()<end){const events=(await get(port,`/sessions/${id}/events?after=0&includeDeltas=1`)).body.events;if(events.some(event=>['turn/completed','turn/failed','turn/interrupted'].includes(event.event_type)))return events;await delay(20);}throw new Error('terminal event was not persisted');}
async function waitTerminalCount(port,id,type,count){const end=Date.now()+10000;let events=[];while(Date.now()<end){events=(await get(port,`/sessions/${id}/events?after=0&includeDeltas=1`)).body.events;if(events.filter(event=>event.event_type===type).length>=count)return events;await delay(30);}throw new Error(`${type} was not persisted: ${JSON.stringify(events)}`);}
async function waitFile(file){const end=Date.now()+10000;while(Date.now()<end){const value=await readFile(file,'utf8').catch(()=>'');if(value)return value;await delay(20);}throw new Error(`${path.basename(file)} was not written`);}
async function waitPidGone(pid){const end=Date.now()+10000;while(Date.now()<end){try{process.kill(pid,0)}catch(error){if(error?.code==='ESRCH')return;}await delay(20);}throw new Error(`pid ${pid} still exists`);}
async function waitDb(file,predicate){const end=Date.now()+10000;while(Date.now()<end){try{const db=new Database(file,{readonly:true}),ready=predicate(db);db.close();if(ready)return;}catch{}await delay(20);}throw new Error('database condition was not reached');}
async function waitFileCount(dir,count){const end=Date.now()+10000;while(Date.now()<end){if((await readdir(dir).catch(()=>[])).filter(name=>name.endsWith('.json')).length===count)return;await delay(20);}throw new Error('sidecar count was not reached');}
async function clearPidFiles(...files){await Promise.all(files.map(file=>rm(file,{force:true})));}
async function assertProcessTreeGone(pids){await delay(30);for(const pid of pids){assert.ok(Number.isInteger(pid)&&pid>1);assert.throws(()=>process.kill(pid,0),error=>error?.code==='ESRCH',`process ${pid} is still alive`);}}
async function get(port,url){const response=await fetch(`http://127.0.0.1:${port}${url}`);return{status:response.status,body:await response.json()};}
async function post(port,url,body){const response=await fetch(`http://127.0.0.1:${port}${url}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return{status:response.status,body:await response.json()};}
async function waitHttp(port,url,child,output){const end=Date.now()+10000;while(Date.now()<end){if(child.exitCode!==null)throw new Error(`runtime exited\n${output.join('')}`);try{if((await fetch(`http://127.0.0.1:${port}${url}`)).ok)return;}catch{}await delay(30);}throw new Error(`runtime unavailable\n${output.join('')}`);}
function freePort(){return new Promise((resolve,reject)=>{const server=net.createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();server.close(()=>resolve(address.port));});});}
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const escapeRegex=value=>String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
