import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {chmod,mkdir,mkdtemp,rm,writeFile} from 'node:fs/promises';
import net from 'node:net';import os from 'node:os';import path from 'node:path';
import test from 'node:test';import Database from 'better-sqlite3';import WebSocket from 'ws';
const root=path.resolve(new URL('../..',import.meta.url).pathname);

test('stale Web cursor, rapid reconnect, and two Runtime restarts converge',{timeout:75_000},async()=>{
  const dir=await mkdtemp(path.join(os.tmpdir(),'agentdeck-restart-e2e-')),runtimePort=await port(),webPort=await port(),profileId='abcdef0123456789',profileHome=path.join(dir,'antigravity-profiles',profileId,'home'),agyBin=path.join(dir,'agy'),workspace=path.join(dir,'workspace');
  await mkdir(path.join(workspace,'src'),{recursive:true});await writeFile(path.join(workspace,'src','app.ts'),'export const before = true;\n');await mkdir(profileHome,{recursive:true});await writeFile(agyBin,`#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';const args=process.argv.slice(2);if(args.includes('--version')){console.log('agy 1.1.2');process.exit(0)}if(args[0]==='models')process.exit(1);const log=args[args.indexOf('--log-file')+1],id='ce69f19b-3085-4abf-b514-03b7e4d0813a',dir=path.join(process.env.HOME,'.gemini','antigravity-cli','conversations');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.db'),'');fs.writeFileSync(log,'Print mode: conversation='+id+', sending message');fs.writeFileSync(path.join(process.cwd(),'src','app.ts'),'export const after = true;\\n');fs.mkdirSync(path.join(process.cwd(),'reports'),{recursive:true});fs.writeFileSync(path.join(process.cwd(),'reports','result.json'),'{"ok":true}\\n');process.stdout.write('durable ');setTimeout(()=>{process.stdout.write('antigravity reply\\n')},1500);`);await chmod(agyBin,0o755);
  const logs={runtime:[],web:[]};let runtime,web,ws;
  const env={...process.env,NODE_ENV:'test',DATA_DIR:dir,RUNTIME_DATA_DIR:dir,RUNTIME_DB:path.join(dir,'runtime.sqlite3'),RUNTIME_TOKEN:'test-runtime-token',AGENT_RUNTIME_TOKEN:'test-runtime-token',AGENT_RUNTIME_URL:`http://127.0.0.1:${runtimePort}`,ANTIGRAVITY_BIN:agyBin,COOKIE_SECRET:'test-cookie-secret-that-is-long-enough',COOKIE_SECURE:'false',ADMIN_PASSWORD:'test-admin-password',USE_AGENT_RUNTIME:'1',HOST:'127.0.0.1',PORT:String(webPort),RUNTIME_HOST:'127.0.0.1',RUNTIME_PORT:String(runtimePort),RUNTIME_DRAIN_TIMEOUT_MS:'500',ALLOWED_ORIGINS:`http://127.0.0.1:${webPort}`,ALLOWED_WORKSPACES:workspace,DEFAULT_WORKDIR:workspace};
  const start=(kind,file)=>{const child=spawn(process.execPath,[file],{cwd:root,env,stdio:['ignore','pipe','pipe']});for(const stream of[child.stdout,child.stderr])stream.on('data',chunk=>logs[kind].push(String(chunk)));return child;};
  try{
    runtime=start('runtime','server/dist/agentdeck-runtime.js');web=start('web','server/dist/index.js');
    await waitJson(`http://127.0.0.1:${runtimePort}/healthz`);await waitJson(`http://127.0.0.1:${webPort}/api/status`);
    seed(path.join(dir,'runtime.sqlite3'),true,workspace,profileId,profileHome);seed(path.join(dir,'agentdeck.sqlite3'),false,workspace,profileId,profileHome);setIngestionCursor(path.join(dir,'agentdeck.sqlite3'),200,'old-runtime');
    web.kill('SIGTERM');await onceExit(web);web=start('web','server/dist/index.js');await waitJson(`http://127.0.0.1:${webPort}/api/status`);
    const origin=`http://127.0.0.1:${webPort}`;
    const login=await fetch(`${origin}/api/login`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({username:'admin',password:'test-admin-password'})});
    if(!login.ok)throw new Error(`login ${login.status}: ${await login.text()}`);
    const cookies=login.headers.getSetCookie().map(value=>value.split(';')[0]),cookie=cookies.join('; '),csrf=cookies.find(value=>value.startsWith('agentdeck_csrf='))?.split('=')[1]||'';
    let agyWs=new WebSocket(`ws://127.0.0.1:${webPort}/ws`,{headers:{cookie,origin}});await onceOpen(agyWs);const agyFrames=[];agyWs.on('message',data=>agyFrames.push(JSON.parse(String(data))));agyWs.send(JSON.stringify({type:'join',sessionId:'agy-refresh',lastSequence:1,clientAppliedSequence:1,snapshotCoveredSequence:1,clientConnectionId:'antigravity-browser-one',joinRequestId:'agy-running',recoveryEpoch:0,runtimeGeneration:''}));await wait(()=>agyFrames.some(frame=>frame.type==='joined'&&frame.sessionId==='agy-refresh'));
    agyWs.send(JSON.stringify({type:'send',sessionId:'agy-refresh',clientMessageId:'agy-turn',text:'canonical question',attachments:[],planMode:'direct'}));await wait(()=>agyFrames.some(frame=>frame.method==='item/agentMessage/delta'));const activeAgy=await fetch(`${origin}/api/sessions/agy-refresh`,{headers:{cookie}}).then(r=>r.json());assert.equal(activeAgy.session.status,'running');assert.equal(activeAgy.session.activeTurn.turnId,'agy-turn');agyWs.send(JSON.stringify({type:'send',sessionId:'agy-refresh',clientMessageId:'agy-followup',text:'second while running',attachments:[],planMode:'direct'}));await wait(()=>agyFrames.some(frame=>frame.type==='messageStatus'&&frame.clientMessageId==='agy-followup'&&frame.status==='failed'));const stale=Math.max(1,...agyFrames.map(frame=>Number(frame.runtimeSequence||0)));
    web.kill('SIGTERM');await onceExit(web);await onceWsClose(agyWs);await wait(()=>runtimeTerminalCount(path.join(dir,'runtime.sqlite3'),'agy-refresh')===1,15_000);web=start('web','server/dist/index.js');await waitJson(`http://127.0.0.1:${webPort}/api/status`);
    agyWs=new WebSocket(`ws://127.0.0.1:${webPort}/ws`,{headers:{cookie,origin}});await onceOpen(agyWs);agyWs.on('message',data=>agyFrames.push(JSON.parse(String(data))));agyWs.send(JSON.stringify({type:'join',sessionId:'agy-refresh',lastSequence:stale,clientAppliedSequence:stale,snapshotCoveredSequence:stale,clientConnectionId:'antigravity-browser-two',joinRequestId:'agy-stale-replay',recoveryEpoch:1,runtimeGeneration:''}));await wait(()=>agyFrames.some(frame=>frame.joinRequestId==='agy-stale-replay'&&frame.type==='joined'));await wait(()=>JSON.stringify(agyFrames).includes('durable antigravity reply'),15_000);await wait(()=>agyFrames.filter(frame=>frame.method==='turn/completed').length===1,15_000);const agyJson=JSON.stringify(agyFrames);assert.equal((agyJson.match(/durable antigravity reply/g)||[]).length,1);assert.equal(agyFrames.filter(frame=>frame.method==='turn/completed').length,1);agyWs.close();await onceWsClose(agyWs);
    const refreshedAgy=await fetch(`${origin}/api/sessions/agy-refresh`,{headers:{cookie}}).then(r=>r.json()),artifactState=readArtifactState(path.join(dir,'agentdeck.sqlite3'));assert.equal(assistantTexts(refreshedAgy).includes('durable antigravity reply'),true);assert.deepEqual(userTexts(refreshedAgy).filter(text=>['canonical question','second while running'].includes(text)),['canonical question','second while running']);assert.deepEqual(relevantConversationOrder(refreshedAgy),['user:canonical question','assistant:durable antigravity reply','user:second while running']);assert.deepEqual(userTurnIds(refreshedAgy).filter(row=>['canonical question','second while running'].includes(row.text)),[{text:'canonical question',turnId:'agy-turn'},{text:'second while running',turnId:'agy-followup'}]);assert.deepEqual(codeChangePaths(refreshedAgy),['src/app.ts'],JSON.stringify(artifactState));assert.deepEqual(artifactPaths(refreshedAgy),['reports/result.json'],JSON.stringify(artifactState));assert.equal(artifactAnchors(refreshedAgy).length,1);assert.ok(artifactAnchors(refreshedAgy)[0]);
    const newContextAgy=await fetch(`${origin}/api/sessions/agy-refresh`,{headers:{cookie}}).then(r=>r.json());assert.equal(assistantTexts(newContextAgy).filter(text=>text==='durable antigravity reply').length,1);
    const patched=await fetch(`${origin}/api/sessions/s`,{method:'PATCH',headers:{cookie,origin,'x-csrf-token':csrf,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5.1'})});
    if(!patched.ok)throw new Error(`patch ${patched.status}: ${await patched.text()}`);const applied=await patched.json();assert.ok(applied.modelRevision>=1);
    const snapshot=await fetch(`${origin}/api/sessions/s`,{headers:{cookie}}).then(r=>r.json());assert.equal(snapshot.session.modelRevision,applied.modelRevision);
    const dashboard=await fetch(`${origin}/api/dashboard`,{headers:{cookie}}).then(r=>r.json());assert.equal(dashboard.sessions.find(session=>session.id==='s').modelRevision,applied.modelRevision);
    ws=new WebSocket(`ws://127.0.0.1:${webPort}/ws`,{headers:{cookie,origin}});await onceOpen(ws);const frames=[];ws.on('message',data=>frames.push(JSON.parse(String(data))));
    ws.send(JSON.stringify({type:'join',sessionId:'s',lastSequence:0,clientAppliedSequence:0,snapshotCoveredSequence:0,clientConnectionId:'isolated-client-uuid',joinRequestId:'join-1',recoveryEpoch:0,runtimeGeneration:''}));await wait(()=>frames.some(frame=>frame.type==='joined'));
    assert.equal(readCursor(path.join(dir,'agentdeck.sqlite3')).sequence,0);assert.notEqual(readCursor(path.join(dir,'agentdeck.sqlite3')).generation,'old-runtime');
    ws.close();await onceWsClose(ws);ws=new WebSocket(`ws://127.0.0.1:${webPort}/ws`,{headers:{cookie,origin}});await onceOpen(ws);ws.on('message',data=>frames.push(JSON.parse(String(data))));ws.send(JSON.stringify({type:'join',sessionId:'s',lastSequence:0,clientAppliedSequence:0,snapshotCoveredSequence:0,clientConnectionId:'isolated-client-uuid-2',joinRequestId:'join-fast',recoveryEpoch:0,runtimeGeneration:''}));await wait(()=>frames.some(frame=>frame.joinRequestId==='join-fast'));
    assert.equal(logs.runtime.join('').match(/runtime sse subscriber connected/g)?.length||0,3,'the Web restart opens one replacement Antigravity subscription while same-Web browser reconnects reuse it');
    runtime.kill('SIGTERM');await onceExit(runtime);const failedPatch=await fetch(`${origin}/api/sessions/s`,{method:'PATCH',headers:{cookie,origin,'x-csrf-token':csrf,'content-type':'application/json'},body:JSON.stringify({model:'must-not-stick'})});assert.equal(failedPatch.ok,false);assert.equal(readModel(path.join(dir,'agentdeck.sqlite3')),'gpt-5.1');insertEvent(path.join(dir,'runtime.sqlite3'),1,'thread_recovered_with_new_upstream',{warning:'restart marker'});runtime=start('runtime','server/dist/agentdeck-runtime.js');await waitJson(`http://127.0.0.1:${runtimePort}/healthz`);
    await wait(()=>readCursor(path.join(dir,'agentdeck.sqlite3')).sequence===1,15_000);ws.send(JSON.stringify({type:'join',sessionId:'s',lastSequence:0,clientAppliedSequence:0,snapshotCoveredSequence:0,clientConnectionId:'isolated-client-uuid-2',joinRequestId:'join-recovery-1',recoveryEpoch:1,runtimeGeneration:readCursor(path.join(dir,'agentdeck.sqlite3')).generation,runtimeGenerationRecovery:true}));await wait(()=>frames.filter(frame=>frame.runtimeSequence===1).length===2&&frames.some(frame=>frame.type==='runtimeConnection'&&frame.status==='connected'),15_000);
    const durable=frames.filter(frame=>frame.runtimeSequence===1);assert.deepEqual(durable.map(frame=>frame.frameIndex),[0,1]);assert.ok(durable.every(frame=>frame.frameCount===2));assert.equal(new Set(durable.map(frame=>`${frame.runtimeSequence}:${frame.frameIndex}`)).size,2);
    runtime.kill('SIGTERM');await onceExit(runtime);insertEvent(path.join(dir,'runtime.sqlite3'),2,'system',{text:'second restart'});runtime=start('runtime','server/dist/agentdeck-runtime.js');await waitJson(`http://127.0.0.1:${runtimePort}/healthz`);await wait(()=>readCursor(path.join(dir,'agentdeck.sqlite3')).sequence===2,15_000);ws.send(JSON.stringify({type:'join',sessionId:'s',lastSequence:1,clientAppliedSequence:1,snapshotCoveredSequence:1,clientConnectionId:'isolated-client-uuid-2',joinRequestId:'join-recovery-2',recoveryEpoch:2,runtimeGeneration:readCursor(path.join(dir,'agentdeck.sqlite3')).generation,runtimeGenerationRecovery:true}));await wait(()=>frames.some(frame=>frame.runtimeSequence===2),15_000);assert.equal(readCursor(path.join(dir,'agentdeck.sqlite3')).sequence,2);
    const after=await fetch(`${origin}/api/sessions/s`,{headers:{cookie}}).then(r=>r.json());assert.equal(after.session.model,'gpt-5.1');assert.equal(after.session.modelRevision,applied.modelRevision);const agyAfterRestart=await fetch(`${origin}/api/sessions/agy-refresh`,{headers:{cookie}}).then(r=>r.json());assert.equal(assistantTexts(agyAfterRestart).includes('durable antigravity reply'),true);assert.deepEqual(assistantTexts(agyAfterRestart),assistantTexts(refreshedAgy));const agyCovered=Number(agyAfterRestart.snapshot.coveredSequence);agyWs=new WebSocket(`ws://127.0.0.1:${webPort}/ws`,{headers:{cookie,origin}});await onceOpen(agyWs);const restartFrames=[];agyWs.on('message',data=>restartFrames.push(JSON.parse(String(data))));agyWs.send(JSON.stringify({type:'join',sessionId:'agy-refresh',lastSequence:agyCovered,clientAppliedSequence:agyCovered,snapshotCoveredSequence:agyCovered,clientConnectionId:'antigravity-after-restart',joinRequestId:'agy-after-restart',recoveryEpoch:2,runtimeGeneration:''}));await wait(()=>restartFrames.some(frame=>frame.type==='joined'));assert.equal(agyAfterRestart.session.status,'idle');agyWs.close();await onceWsClose(agyWs);
  }catch(error){throw new Error(`${error?.stack||error}\nRuntime tail:\n${logs.runtime.join('').slice(-8000)}\nWeb tail:\n${logs.web.join('').slice(-8000)}`);}
  finally{try{ws?.close();}catch{}for(const child of[runtime,web])if(child&&!child.killed)child.kill('SIGTERM');await Promise.all([runtime,web].filter(Boolean).map(child=>onceExit(child).catch(()=>{})));await rm(dir,{recursive:true,force:true});}
});
function seed(file,isRuntime,workspace,profileId,profileHome){
  const db=new Database(file);
  for(const sql of ['ALTER TABLE sessions ADD COLUMN model_id TEXT','ALTER TABLE sessions ADD COLUMN model_revision INTEGER NOT NULL DEFAULT 0','ALTER TABLE sessions ADD COLUMN provider_id TEXT','ALTER TABLE sessions ADD COLUMN last_sequence INTEGER NOT NULL DEFAULT 0','ALTER TABLE sessions ADD COLUMN active_turn_id TEXT'])try{db.exec(sql);}catch{}
  db.prepare("INSERT OR REPLACE INTO sessions(id,codex_thread_id,project_dir,title,status,permission_mode,approval_policy,sandbox_mode,model,model_id,model_revision,archived,created_at,updated_at,provider_id,last_sequence)VALUES('s','s',?,'Restart','idle','yolo','never','full-access','gpt-5','gpt-5',0,0,1,1,'codex',0)").run(workspace);
  db.prepare("INSERT OR REPLACE INTO sessions(id,codex_thread_id,project_dir,title,status,active_turn_id,permission_mode,approval_policy,sandbox_mode,archived,created_at,updated_at,provider_id,last_sequence,account_id)VALUES('agy-refresh','agy-refresh',?,'Antigravity refresh','idle',NULL,'workspace-write','on-request','workspace-write',0,1,1,'antigravity',1,?)").run(workspace,profileId);
  if(isRuntime)insertEventDb(db,'agy-refresh',1,'user',{input:[{type:'text',text:'historical question'}],turnId:'historical-turn',segmentId:'historical-turn',clientMessageId:'historical-client'});
  else{db.prepare("INSERT OR REPLACE INTO antigravity_profiles(id,name,home_dir,active,status,created_at,updated_at)VALUES(?,'Restart profile',?,1,'authenticated',1,1)").run(profileId,profileHome);db.prepare("INSERT OR REPLACE INTO agent_messages(id,session_id,role,text,original_text,created_at,client_message_id,turn_id,segment_id,status)VALUES('historical-user','agy-refresh','user','historical question','historical question',1,'historical-client','historical-turn','historical-turn','accepted')").run();}
  db.close();
}
function markAgyRunning(file){const db=new Database(file);db.prepare("UPDATE sessions SET status='running',active_turn_id='agy-turn' WHERE id='agy-refresh'").run();db.close();}
function completeAgy(file){const db=new Database(file);insertEventDb(db,'agy-refresh',2,'item/completed',{method:'item/completed',params:{item:{id:'agy-answer',type:'agentMessage',text:'durable antigravity reply',phase:'final_answer'}}});insertEventDb(db,'agy-refresh',3,'turn/completed',{method:'turn/completed',params:{turn:{id:'agy-turn',status:'completed'}}});db.prepare("UPDATE sessions SET status='idle',active_turn_id=NULL,last_sequence=3 WHERE id='agy-refresh'").run();db.close();}
function insertEventDb(db,sessionId,sequence,type,payload){const now=Date.now(),json=JSON.stringify(payload);db.prepare('INSERT INTO events(session_id,ts,kind,payload,sequence,event_type,payload_json,created_at,event_key)VALUES(?,?,?,?,?,?,?,?,NULL)').run(sessionId,now,type,json,sequence,type,json,now);db.prepare('UPDATE sessions SET last_sequence=? WHERE id=?').run(sequence,sessionId);}
function assistantTexts(snapshot){return(snapshot.thread?.turns||[]).flatMap(turn=>turn.items||[]).filter(item=>item.type==='agentMessage').map(item=>item.text);}
function userTexts(snapshot){return(snapshot.thread?.turns||[]).flatMap(turn=>turn.items||[]).filter(item=>item.type==='userMessage').map(item=>String(item.originalText||item.text||item.content?.[0]?.text||''));}
function relevantConversationOrder(snapshot){return(snapshot.thread?.turns||[]).flatMap(turn=>turn.items||[]).flatMap(item=>{const text=item.type==='userMessage'?String(item.originalText||item.text||item.content?.[0]?.text||''):item.type==='agentMessage'?String(item.text||''):'';return['canonical question','durable antigravity reply','second while running'].includes(text)?[`${item.type==='userMessage'?'user':'assistant'}:${text}`]:[];});}
function userTurnIds(snapshot){return(snapshot.thread?.turns||[]).flatMap(turn=>(turn.items||[]).filter(item=>item.type==='userMessage').map(item=>({text:String(item.originalText||item.text||item.content?.[0]?.text||''),turnId:String(item.turnId||turn.turnId||turn.id||'')})));}
function codeChangePaths(snapshot){return(snapshot.thread?.turns||[]).flatMap(turn=>turn.items||[]).filter(item=>item.type==='codeChanges').flatMap(item=>item.changes||[]).map(change=>change.path);}
function artifactPaths(snapshot){return(snapshot.thread?.turns||[]).flatMap(turn=>turn.items||[]).filter(item=>item.type==='artifactCollection').flatMap(item=>item.artifacts||[]).map(item=>item.relativePath);}
function artifactAnchors(snapshot){return(snapshot.thread?.turns||[]).flatMap(turn=>turn.items||[]).filter(item=>item.type==='artifactCollection').flatMap(item=>item.artifacts||[]).map(item=>item.anchorItemId);}
async function runtimePost(portNumber,url,body){const response=await fetch(`http://127.0.0.1:${portNumber}${url}`,{method:'POST',headers:{authorization:'Bearer test-runtime-token','content-type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`runtime POST ${url}: ${response.status} ${await response.text()}`);return response.json();}
function runtimeTerminalCount(file,sessionId){const db=new Database(file,{readonly:true}),count=db.prepare("SELECT COUNT(*) FROM events WHERE session_id=? AND event_type IN ('turn/completed','turn/failed','turn/interrupted')").pluck().get(sessionId);db.close();return Number(count);}
function insertEvent(file,sequence,type,payload){const db=new Database(file),now=Date.now(),json=JSON.stringify(payload);db.prepare('INSERT INTO events(session_id,ts,kind,payload,sequence,event_type,payload_json,created_at,event_key)VALUES(?,?,?,?,?,?,?,?,NULL)').run('s',now,type,json,sequence,type,json,now);db.prepare('UPDATE sessions SET last_sequence=? WHERE id=?').run(sequence,'s');db.close();}
function setIngestionCursor(file,sequence,generation){const db=new Database(file);db.prepare('INSERT OR REPLACE INTO runtime_ingestion_cursors(session_id,committed_sequence,runtime_generation,updated_at)VALUES(?,?,?,?)').run('s',sequence,generation,Date.now());db.close();}
function readCursor(file){const db=new Database(file,{readonly:true}),row=db.prepare("SELECT committed_sequence sequence,runtime_generation generation FROM runtime_ingestion_cursors WHERE session_id='s'").get();db.close();return row;}
function readModel(file){const db=new Database(file,{readonly:true});const model=db.prepare("SELECT model FROM sessions WHERE id='s'").pluck().get();db.close();return model;}
function readArtifactState(file){const db=new Database(file,{readonly:true}),state={baselines:db.prepare("SELECT session_id,turn_id,project_dir FROM artifact_baselines WHERE session_id='agy-refresh'").all(),artifacts:db.prepare("SELECT turn_id,relative_path,anchor_item_id FROM artifacts WHERE session_id='agy-refresh'").all(),changes:db.prepare("SELECT turn_id,changes_json,anchor_item_id FROM turn_code_changes WHERE session_id='agy-refresh'").all()};db.close();return state;}
function port(){return new Promise((resolve,reject)=>{const server=net.createServer();server.listen(0,'127.0.0.1',()=>{const value=server.address().port;server.close(error=>error?reject(error):resolve(value));});server.on('error',reject);});}
async function waitJson(url){let last;for(let i=0;i<100;i++){try{const response=await fetch(url,{headers:{authorization:'Bearer test-runtime-token'}});if(response.ok)return response.json();last=new Error(`${response.status}`);}catch(error){last=error;}await new Promise(resolve=>setTimeout(resolve,100));}throw last;}
async function wait(predicate,timeout=10_000){const end=Date.now()+timeout;while(Date.now()<end){if(predicate())return;await new Promise(resolve=>setTimeout(resolve,25));}throw new Error('condition timeout');}
function onceOpen(ws){return new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject);});}
function onceWsClose(ws){return new Promise(resolve=>{if(ws.readyState===WebSocket.CLOSED)return resolve();ws.once('close',resolve);});}
function onceExit(child){return new Promise(resolve=>{if(child.exitCode!==null||child.signalCode!==null)return resolve();child.once('exit',resolve);});}
