import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import test from 'node:test';
import {Db} from '../server/dist/db.js';import {DurableEventStore} from '../server/dist/event-store.js';

async function fixture(){const dir=await mkdtemp(path.join(os.tmpdir(),'agentdeck-event-order-')),db=new Db(path.join(dir,'db.sqlite'));await db.init();for(const sql of ['ALTER TABLE events ADD COLUMN sequence INTEGER','ALTER TABLE events ADD COLUMN event_type TEXT','ALTER TABLE events ADD COLUMN payload_json TEXT','ALTER TABLE events ADD COLUMN created_at INTEGER','ALTER TABLE events ADD COLUMN event_key TEXT','ALTER TABLE sessions ADD COLUMN last_sequence INTEGER NOT NULL DEFAULT 0'])await db.run(sql).catch(()=>{});await db.run('CREATE UNIQUE INDEX IF NOT EXISTS test_event_sequence ON events(session_id,sequence)');await db.run('CREATE UNIQUE INDEX IF NOT EXISTS test_event_key ON events(session_id,event_key)');await db.run("INSERT INTO sessions (id,codex_thread_id,project_dir,title,status,permission_mode,approval_policy,sandbox_mode,archived,created_at,updated_at,last_sequence) VALUES ('s','s','/tmp','s','idle','yolo','never','full-access',0,1,1,0)");return{db,dir,close:async()=>{db.close();await rm(dir,{recursive:true,force:true});}};}

test('delta delta critical critical preserve append call order',async()=>{const f=await fixture();try{const store=new DurableEventStore(f.db,'g',{windowMs:1000});const promises=[store.append('s','d1',{x:'1'},null,false,true),store.append('s','d2',{x:'2'},null,false,true),store.append('s','criticalA',{},null,true,false),store.append('s','criticalB',{},null,true,false)];await Promise.all(promises);assert.deepEqual((await f.db.all('SELECT sequence,event_type FROM events ORDER BY sequence')).map(r=>[r.sequence,r.event_type]),[[1,'d1'],[2,'d2'],[3,'criticalA'],[4,'criticalB']]);}finally{await f.close();}});

test('concurrent duplicate event key consumes one sequence',async()=>{const f=await fixture();try{const store=new DurableEventStore(f.db,'g');const [a,b]=await Promise.all([store.append('s','critical',{},'same',true,false),store.append('s','critical',{},'same',true,false)]);assert.equal(a.sequence,1);assert.equal(b.sequence,1);assert.equal((await f.db.get('SELECT COUNT(*) AS count FROM events')).count,1);}finally{await f.close();}});

test('sqlite failure is followed by a contiguous successful sequence',async()=>{const f=await fixture();try{const original=f.db.transactionRun.bind(f.db);let fail=true;f.db.transactionRun=(statements)=>{if(fail){fail=false;throw new Error('injected write failure');}return original(statements);};const store=new DurableEventStore(f.db,'g');await assert.rejects(store.append('s','first',{},null,true,false),/injected/);const event=await store.append('s','second',{},null,true,false);assert.equal(event.sequence,1);assert.deepEqual((await f.db.all('SELECT sequence FROM events')).map(r=>r.sequence),[1]);}finally{await f.close();}});

test('maxBytes flushes a delta batch without waiting for timer',async()=>{const f=await fixture();try{const store=new DurableEventStore(f.db,'g',{windowMs:60_000,maxBytes:10});const event=await store.append('s','delta',{text:'payload larger than limit'},null,false,true);assert.equal(event.sequence,1);assert.equal(store.metrics.deltaQueueBytes,0);}finally{await f.close();}});
