import assert from'node:assert/strict';import{execFileSync,spawnSync}from'node:child_process';import{existsSync,mkdtempSync,mkdirSync,readFileSync,readlinkSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import test from'node:test';
const repo=new URL('..',import.meta.url).pathname,ctl=join(repo,'scripts/agentdeckctl');
function shell(body,env={}){const root=mkdtempSync(join(tmpdir(),'agentdeck-safe-deploy-'));mkdirSync(join(root,'data'),{recursive:true});try{return execFileSync('bash',['-c',`source "$CTL"; ensure_dirs; ${body}`],{encoding:'utf8',env:{...process.env,CTL:ctl,ROOT:root,AGENTDECK_ROOT:root,AGENTDECK_SOURCE_ROOT:repo,AGENTDECK_DEPLOY_STATE_DIR:join(root,'state'),DATA_DIR:join(root,'data'),...env}});}finally{rmSync(root,{recursive:true,force:true});}}
test('wait_drain ignores activeTurnCount zero until drained is explicitly true',()=>{const out=shell(`echo 0 > "$ROOT/n"; drain_status(){ n=$(cat "$ROOT/n");n=$((n+1));echo "$n" > "$ROOT/n";[ "$n" -lt 3 ] && echo '{"activeTurnCount":0,"drained":false}' || echo '{"activeTurnCount":0,"drained":true}'; }; drain_runtime(){ :; }; undrain_runtime(){ echo undrain; }; sleep(){ :; }; wait_drain 0; echo calls=$(cat "$ROOT/n")`);assert.match(out,/calls=3/);assert.doesNotMatch(out,/undrain/);});
test('drain timeout cancels and undrains without restarting runtime',()=>{const out=spawnSync('bash',['-c',`source "$CTL"; drain_status(){ echo '{"drained":false,"outputDraining":1}'; }; drain_runtime(){ :; }; undrain_runtime(){ echo undrained; }; sleep(){ :; }; DRAIN_TIMEOUT_SECONDS=0; wait_drain 0`],{encoding:'utf8',env:{...process.env,CTL:ctl}});assert.notEqual(out.status,0);assert.match(out.stdout,/undrained/);});
test('final drain recheck failure prevents pointer switch and systemctl restart',()=>{const source=readFileSync(ctl,'utf8');assert.match(source,/if ! require_runtime_drained; then rm -f "\$pointer_snapshot"; exit 1; fi\s+switch_component runtime/);assert.match(source,/final runtime drain check was not drained=true/);});
test('a long turn appearing in the final check leaves the runtime pointer and PID untouched',()=>{const root=mkdtempSync(join(tmpdir(),'agentdeck-final-drain-')),data=join(root,'data');mkdirSync(data,{recursive:true});const script=`source "$CTL";ensure_dirs;mkdir -p "$RELEASES_DIR/old" "$RELEASES_DIR/prev";ln -s releases/old "$CURRENT_RUNTIME_LINK";ln -s releases/prev "$PREVIOUS_RUNTIME_LINK";verify_runtime_systemd_contract(){ :; };make_release(){ mkdir -p "$RELEASES_DIR/new";CREATED_RELEASE_ID=new; };assert_release_unit_requirement(){ :; };check_systemd_units(){ :; };start_candidate_runtime(){ :; };validate_candidate_runtime_compatibility(){ :; };drain_runtime(){ :; };wait_drain(){ :; };require_runtime_drained(){ return 1; };undrain_runtime(){ :; };cleanup_releases(){ :; };systemctl(){ echo called >> "$ROOT/systemctl"; };write_job test accepted accepted;worker_deploy test runtime 0`;const run=spawnSync('bash',['-c',script],{encoding:'utf8',env:{...process.env,CTL:ctl,ROOT:root,AGENTDECK_ROOT:root,AGENTDECK_SOURCE_ROOT:repo,AGENTDECK_DEPLOY_STATE_DIR:join(root,'state'),DATA_DIR:data}});try{assert.notEqual(run.status,0);assert.equal(readlinkSync(join(root,'current-runtime')),'releases/old');assert.equal(existsSync(join(root,'systemctl')),false);}finally{rmSync(root,{recursive:true,force:true});}});
test('deploy worker creates only candidate SQLite copies and never invokes formal backup',()=>{const body=readFileSync(ctl,'utf8').slice(readFileSync(ctl,'utf8').indexOf('worker_deploy()'),readFileSync(ctl,'utf8').indexOf('worker_rollback()'));assert.match(body,/start_candidate_runtime/);assert.doesNotMatch(body,/run_backup|agentdeck-backup-/);});
test('backup manifest initialization is safe under nounset',()=>{const source=readFileSync(ctl,'utf8');assert.match(source,/local file="\$1" include_secrets="\$2" root="\$3" checksums\s+checksums="\$root\/checksums\.tsv"/);});
