export type ProviderId = 'codex'|'claude'|'antigravity'|'gemini';
export type ProviderAvailability = 'checking'|'ready'|'unavailable'|'error';
export type ProviderAuth = 'checking'|'authenticated'|'unauthenticated'|'authenticating'|'unknown'|'not_applicable'|'error';
export type AccountSummary = {profileId?:string;providerAccountId?:string;email?:string;displayName?:string;authType?:string};
export type ProviderStatus = { provider?:ProviderId; id:ProviderId; displayName:string; availability?:ProviderAvailability; auth?:ProviderAuth; accountSummary?:AccountSummary|null; account?:{id?:string;email?:string;displayName?:string;profileId?:string;authType?:string}|null; version?:string|null; activeProfileId?:string|null; canCreateSession?:boolean; canContinueSession?:boolean; canManageAccounts?:boolean; canLogout?:boolean; canQueryQuota?:boolean; canListModels?:boolean; canSelectModel?:boolean; capabilities?:Record<string,any>; reasonCode?:string|null; message?:string|null; checkedAt?:string; ok:boolean; installed:boolean; error?:string|null; installHint?:string; runtime?:any };
export type ProviderInstallJob = {id:string;provider:ProviderId;action:string;status:string;output:string[];error?:string|null;version?:string|null;startedAt:number;updatedAt:number};
export type ProviderInstaller = {provider:ProviderId;automatic:boolean;binary:string;packageName?:string|null;source:string;reason:string;manual:string;latestJob?:ProviderInstallJob|null};
export type Capabilities = { imageInput:boolean; imageOutput:boolean; fileInput?:boolean; attachmentTypes:string[]; maxAttachmentBytes:number; maxAttachmentsPerMessage?:number; maxTotalAttachmentBytes?:number; providers?:Record<string,any> };
export type Status = { authed:boolean; roots:string[]; mode:string; defaultMode:string; defaultWorkspace?:string; defaultModel?:string; defaultModels?:Record<string,string>; activeProvider?:ProviderId; codex:any; claude?:ProviderStatus; gemini?:ProviderStatus; antigravity?:ProviderStatus; providers?:ProviderStatus[]; providerDefinitions?:Array<{id:ProviderId;visible?:boolean}>; providerStatus?:Record<ProviderId,ProviderStatus>; runtimeState?:any; release?:any; capabilities:Capabilities; activeProfile?:any; activeClaudeProfile?:any; activeGeminiProfile?:any; activeAntigravityProfile?:any };
export type ActiveTurn = {turnId:string|null; status:string; startedAt?:number|null; waitingKind?:'approval'|'input'|'plan'|null};
export type Session = { id:string; codex_thread_id:string; provider_id?:ProviderId; providerId?:ProviderId; project_dir:string; title:string; status:string; activeTurn?:ActiveTurn|null; permission_mode?:string; approval_policy?:string; sandbox_mode?:string; model?:string|null; modelRevision?:number; archived?:number; created_at?:number; updated_at?:number; last_sequence?:number };
export type Project = { name:string; path:string; branch:string|null; updatedAt:number };
export type DashboardArtifact = {id:string;sessionId:string;name:string;type:string;size:number;updatedAt:number;url:string};
export type Dashboard = { generatedAt:number; archived:boolean; control:Status; artifacts:{total:number;items:DashboardArtifact[]}; metrics:{total:number;running:number;waiting:number;updatedToday:number;projects:number}; activity:{date:string;count:number}[]; projects:{path:string;name:string;sessions:number;lastActiveAt:number}[]; sessions:Session[] };
export type ModelOption = { id:string; model:string; actualModel?:string; displayName:string; description?:string; hidden?:boolean; isDefault?:boolean; inputModalities?:string[]; upgrade?:string|null };
export type Attachment = { id:string; name:string; type:string; size:number; url:string; previewUrl?:string; uploading?:boolean; error?:string; operation?:'created'|'modified'|string; relativePath?:string|null };
export type DisplayEvent = { key:string; role:'user'|'assistant'|'system'|'command'|'file'|'reasoning'|'image'; title?:string; text:string; meta?:string; open?:boolean; clientMessageId?:string; messageId?:string; turnId?:string; segmentId?:string; retryOf?:string; attachments?:Attachment[]; images?:Attachment[]; files?:Attachment[]; deliveryStatus?:string; deliveryError?:string };
export type RuntimeConnection = 'unknown'|'checking'|'recovering'|'connected'|'unavailable'|'disconnected';
export type Toast = { id:string; kind:'success'|'error'|'info'; text:string };
export type ApprovalRequest = { requestId:string; method:string; params:any };
export type PlanRequest = {
  requestId:string;
  sessionId:string;
  turnId:string;
  providerId:ProviderId;
  kind:'plan_review';
  title:string;
  body:string;
  options:{id:string;label:string;description?:string;variant?:'primary'|'secondary'|'danger'}[];
  allowFreeText:boolean;
  defaultOptionId?:string;
  status:'pending'|'answered'|'cancelled'|'expired';
  createdAt:number;
  answeredAt?:number;
  answer?:{optionId?:string;text?:string;metadata?:Record<string,unknown>};
  metadata?:Record<string,any>;
};
